# Generated by Django 4.2 on 2024-06-03 10:38

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicepage",
            name="applications",
        ),
        migrations.RemoveField(
            model_name="servicepage",
            name="intro",
        ),
        migrations.RemoveField(
            model_name="servicepage",
            name="services",
        ),
        migrations.RemoveField(
            model_name="servicepage",
            name="titles",
        ),
        migrations.AddField(
            model_name="servicepage",
            name="first_part",
            field=wagtail.fields.StreamField(
                [("html", wagtail.blocks.RawHTMLBlock())],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="second_part",
            field=wagtail.fields.StreamField(
                [("html", wagtail.blocks.RawHTMLBlock())],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="third_part",
            field=wagtail.fields.StreamField(
                [("html", wagtail.blocks.RawHTMLBlock())],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
