# Generated by Django 4.2 on 2024-06-03 10:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "about_me",
                    wagtail.fields.StreamField(
                        [("html", wagtail.blocks.RawHTMLBlock())],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "brand",
                    wagtail.fields.StreamField(
                        [("html", wagtail.blocks.RawHTMLBlock())],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("nationality", models.CharField(max_length=100)),
                ("freelance_status", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("skype", models.CharField(max_length=100)),
                ("languages", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_information",
                        to="aboutme.resumepage",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Personal Information",
            },
        ),
        migrations.CreateModel(
            name="ExperienceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_year", models.CharField(max_length=20)),
                ("end_year", models.CharField(blank=True, max_length=20, null=True)),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "resume_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_items",
                        to="aboutme.resumepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "resume_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_items",
                        to="aboutme.resumepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Accomplishments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("years_of_experience", models.IntegerField()),
                ("happy_customers", models.IntegerField()),
                ("completed_projects", models.IntegerField()),
                ("awards_won", models.IntegerField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accomplishments",
                        to="aboutme.resumepage",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Accomplishments",
            },
        ),
    ]
